# =========================================================================== #
#### ===================== BRBSEQ - RAW TO PROCESSED ===================== ####
# =========================================================================== #
#### I NEED TO FIX TOPICS 4.3 FOWARD ####
# Date: 01.set.2026
### From a raw count matrix generated by alithea brb-seq library kit, this
## script aims to normalize data, visualize distribution, correct batch
## effect if necessary and produce a processed count matrix to be used in
## applications of expression data that don't include these steps in their
## workflow.
# <-- INPUT:
## + raw count matrix
## + batch data
## + hemoglobin genes 
# --> OUTPUT:
## + distribution plots (.png)
## + histogram and elbow plot of sd (.png)
## + pca biplots (.png)
## + processed count matrix (.RDS)
# =========================================================================== #
#### 0. Libraries -------------------------------------------------------- ####
# =========================================================================== #
library(ggplot2)
library(tidyverse)
library(psych)
library(patchwork)
library(limma)
library(edgeR)
library(sva)
# =========================================================================== #
#### 1. Inputs ----------------------------------------------------------- ####
# =========================================================================== #
## 1.1. Raw count matrix (transcript x sample) ----------------------------- ##
brb.mtx <- readRDS("./brbseq/input/20260902_brbseq_rawCount_mqudi1to6.RDS")
brb.mtx <- as.data.frame(t(brb.mtx))
## 1.2. Batch data --------------------------------------------------------- ##
batch.brb <- read.csv("./brbseq/input/20260902_brbseq_batchData_mqudi1to6.csv")
## 1.3. Hemoglobin genes --------------------------------------------------- ##
hemo <- read.csv("../msc_work/alithea_brbseq/input/gene_hemoglobin.csv")
## 1.4. Theme for ggplot2 -------------------------------------------------- ##
theme_set(theme(plot.title = element_text(hjust = 0.5, face = "bold",
                                          vjust = 1.5, size = 14),
                axis.title = element_text(hjust = 0.5, face = "bold",
                                          size = 11),
                axis.text = element_text(color = "black", size = 9),
                panel.background = element_blank(),
                panel.grid = element_blank(),
                panel.border = element_rect(color = "black"),
                legend.title = element_text(size = 10, face = "bold")))
## 1.5. Output path -------------------------------------------------------- ##
out <- "./brbseq/output/"
# =========================================================================== #
#### 2. QC analysis ------------------------------------------------------ ####
# =========================================================================== #
## 2.1. Sum of total counts for each sample -------------------------------- ##
sum.df <- data.frame("PSID_brb" = colnames(brb.mtx),
                     "sum_count" = colSums(brb.mtx))
## 2.2. Create a adequate object for ggplot visualization ------------------ ##
gg.dt <- merge(sum.df, batch.brb, by = "PSID_brb", all.x = T)
## 2.3. Boxplot of library size by batch ----------------------------------- ##
ggplot(gg.dt, aes(x = Batch, y = sum_count, fill = Batch, group = Batch)) +
  geom_boxplot(color = "black", outliers = F)+
  geom_jitter(width = 0.02)+
  ylab("Sum of raw count")+
  xlab("Batch")+
  labs(title = "Library Sizes by Batch")+
  guides(fill="none")+
  scale_fill_manual(values =c("brown2", "darkslategray3", "violetred3",
                              "slateblue", "indianred1", "deepskyblue2"))
ggsave("02_qc_distribution_librarySize_byBatch.png",
       path = out, width = 7, height = 5)
dev.off()
## 2.4. Distribution of overall library size ------------------------------- ##
ggplot(gg.dt, aes(x = sum_count)) +
  geom_density(alpha = 0.3, fill = "plum4") +
  labs(title = "Density plot of overall library size",
       x = "Sum of raw count", y = "Density")
ggsave("02_qc_density_overall_librarySize.png",
       path = out, width = 7, height = 5)
dev.off()
## 2.5. Distribution of library size by batch ------------------------------ ##
ggplot(gg.dt, aes(x = sum_count, group = Batch, fill = Batch)) +
  geom_density(alpha = 0.6) +
  labs(title = "Density plot of library size by batch",
       x = "Sum of raw count", y = "Density")+
  guides(fill=guide_legend(title="Batch"))+
  scale_fill_manual(values =c("brown", "darkslategray3", "violetred",
                              "slateblue", "indianred1", "deepskyblue2"))
ggsave("02_qc_density_librarySize_byBatch.png",
       path = out, width = 7, height = 5)
dev.off()
## 2.6. Histogram of library size ------------------------------------------ ##
ggplot(gg.dt, aes(x = log10(sum_count))) +
  geom_histogram() +
  labs(title = "Histogram of library size",
       y = "Frequency", x = "Library size (log10)")
ggsave("02_qc_histogram_librarySize.png",
       path = out, width = 7, height = 5)
# =========================================================================== #
#### 3. Normalization ---------------------------------------------------- ####
# =========================================================================== #
## 3.1. If necessary (almost always is), remove batch effect --------------- ##
coldata <- subset(batch.brb, select = c(PSID_brb, Batch))
rownames(coldata) <- coldata$PSID_brb
coldata <- coldata[colnames(lcpm),]
coldata$PSID_brb <- NULL
clean.mtx <- ComBat_seq(counts    = as.matrix(brb.mtx),
                        batch     = coldata$Batch)
## 3.1. Using limma -------------------------------------------------------- ##
dge <- DGEList(counts = clean.mtx)
## 3.2. Filter rows with low count and hemoglobin genes -------------------- ##
keep <- filterByExpr(dge, min.count = 10,
                     min.total.count = 15, 
                     min.prop = 0.25)
keep <- keep & ! rownames(dge) %in% hemo ## remove hemoglobin genes ##
dge <- dge[keep,, keep.lib.sizes = FALSE]
## 3.3. Calculate normalization factors ------------------------------------ ##
dge <- normLibSizes(dge,
                    method = "RLE") ## <<<< RLE or TMM ##
## 3.4. Normalize by log2-CPM ---------------------------------------------- ##
lcpm <- cpm(dge, log = T, prior.count = 3)
# =========================================================================== #
#### 4. Principal Component Analysis (PCA) ------------------------------- ####
# =========================================================================== #
## 4.1. Using all filtered transcripts ------------------------------------- ##
## 4.1.1. Defining PCs ----------------------------------------------------- ##
pc <- prcomp(t(lcpm),
             center = TRUE,
             scale. = TRUE)
summary(pc) 
pairs.panels(pc$x[,1:5],
             gap=0, 
             pch=20)
pca.dt <- data.frame(PC1 = pc$x[, 1],
                     PC2 = pc$x[, 2],
                     PC3 = pc$x[, 3],
                     PC4 = pc$x[, 4],
                     PC5 = pc$x[, 5])
## 4.2.2. Merge with samples data ------------------------------------------ ##
pca.dt$PSID_brb <- rownames(pca.dt)
pca.m <- merge(pca.dt, batch.brb, by = "PSID_brb")
## 4.2.3. Plotting PCs ----------------------------------------------------- ##
pcI <- "PC1 (9.7%)"
pcII <- "PC2 (6.4%)"
pcIII <- "PC3 (5.4%)"
pcIV <- "PC4 (4.1%)"
pcV <- "PC5 (3.2%)"

ggI.II <- ggplot(pca.m, aes(x = PC1, y = PC2, color = Batch)) +
  geom_point(size = 2)+
  labs(title = "PC1 x PC2",
       x = pcI,
       y = pcII) +
  guides(color = "none")+
  scale_color_manual(values =c("brown", "darkslategray3", "violetred",
                               "slateblue", "indianred1", "deepskyblue2"))+
  theme(axis.title.x = element_blank(),
        plot.title = element_text(size = 12))
ggI.III <- ggplot(pca.m, aes(x = PC1, y = PC3, color = Batch)) +
  geom_point(size = 2)+
  labs(title = "PC1 x PC3",
       x = pcI,
       y = pcIII) +
  guides(color = "none")+
  scale_color_manual(values =c("brown", "darkslategray3", "violetred",
                               "slateblue", "indianred1", "deepskyblue2"))+
  theme(axis.title.x = element_blank(),
        plot.title = element_text(size = 12))
ggI.IV <- ggplot(pca.m, aes(x = PC1, y = PC4, color = Batch)) +
  geom_point(size = 2)+
  labs(title = "PC1 x PC4",
       x = pcI,
       y = pcIV) +
  guides(color = "none")+
  scale_color_manual(values =c("brown", "darkslategray3", "violetred",
                               "slateblue", "indianred1", "deepskyblue2"))+
  theme(plot.title = element_text(size = 12))
ggI.V <- ggplot(pca.m, aes(x = PC1, y = PC5, color = Batch)) +
  geom_point(size = 2)+
  labs(title = "PC1 x PC5",
       x = pcI,
       y = pcV) +
  scale_color_manual(values =c("brown", "darkslategray3", "violetred",
                               "slateblue", "indianred1", "deepskyblue2"))+
  theme(plot.title = element_text(size = 12))

(ggI.II + ggI.III + ggI.IV + ggI.V) +
  plot_annotation(title = "PCA for all transcripts after")

ggsave("04_pca_panel_all_transcripts.png",
       path = out, width = 7, height = 7)
dev.off()
## 4.3. Using Most Variable Transcripts (MVT) ------------------------------ ##
## 4.3.1. Visualize the overall standard deviation ------------------------- ##
sd <- apply(int.mtx,1,sd)
png(file.path(out, "04_histogram_sd_all_transcripts.png"), 
    width = 6, height = 4, units = "in", res = 300)
hist(sd, breaks = 100, col = "snow",
     xlab = "Standard Deviation", 
     ylab = "Frequency", main = "Histogram of standard deviation")
abline(v=quantile(sd, 0.50), col = "gray10",lwd = 3, lty = 1)#50%
abline(v=quantile(sd, 0.75), col = "gray30",lwd = 3, lty = 1)#75%
abline(v=quantile(sd, 0.90), col = "gray50",lwd = 3, lty = 1)#90%
abline(v=quantile(sd, 0.99) , col = "gray70",lwd = 3, lty = 1)#95%
legend("right", inset=.02, title="Quantile",
       c("50%","25%","10%","1%"),
       fill=c("gray10", "gray30", "gray50", "gray70"),
       horiz=F, cex=0.8)
box(lwd = 1.5)
dev.off()
## 4.3.2. Elbow plot ------------------------------------------------------- ##
# --------------------------------------------------------------------------- #
# | The inflection point ("elbow") of the curve indicates the threshold     | #
# | where the variation ceases to represent a relevant biological signal    | #
# | and becomes merely background noise.                                    | #
# --------------------------------------------------------------------------- #
## A data frame ordered by highest sd to lowest ##
df.sd <- data.frame(miRNA = names(sd),
                    SD = sd) %>%
  arrange(desc(SD)) %>%
  mutate(Rank = row_number())

ggplot(df.sd, aes(x = Rank, y = SD)) +
  geom_line(color = "paleturquoise2", size = 0.75) +
  geom_point(color = "slateblue", alpha = 0.3, size = 1.5) +
  geom_vline(xintercept = c(100, 250, 500, 1000, 2000), linetype = "dashed",
             color = "orangered", alpha = 0.7) +
  labs(
    title = "Elbow plot of miRNAs by standard deviation",
    x = "miRNAs rank (highest to lowest sd)",
    y = "Standard deviation ")
ggsave("04_elbow_plot.png",
       path = out, width = 7, height = 5)
dev.off()
## 4.3.3. Filter MVT ------------------------------------------------------- ## 
mvt.mtx <- int.mtx[names(sort(sd, decreasing = T))[1:500],]
## 4.3.4. Defining PCs ----------------------------------------------------- ##
pc <- prcomp(t(mvt.mtx),
             center = TRUE,
             scale. = TRUE)
summary(pc) 
pairs.panels(pc$x[,1:5],
             gap=0, 
             pch=20)
pca.dt <- data.frame(PC1 = pc$x[, 1],
                     PC2 = pc$x[, 2],
                     PC3 = pc$x[, 3],
                     PC4 = pc$x[, 4],
                     PC5 = pc$x[, 5])
## 4.3. Merge with samples data -------------------------------------------- ##
pca.dt$sample <- rownames(pca.dt)
pca.m <- merge(pca.dt, data, by = "sample")
## 4.4. Plotting PCs ------------------------------------------------------- ##
pcI <- "PC1 (64.9%)"
pcII <- "PC2 (12.6%)"
pcIII <- "PC3 (8.8%)"
pcIV <- "PC4 (4.6%)"
pcV <- "PC5 (3.8%)"

ggI.II <- ggplot(pca.m, aes(x = PC1, y = PC2, color = condition)) +
  geom_point(size = 2)+
  geom_text(aes(label = sample), size = 2, color = "black")+
  labs(title = "PC1 x PC2",
       x = pcI,
       y = pcII) +
  guides(color = "none")+
  scale_color_manual(values = c("brown2", "darkslategray3"))+
  theme(axis.title.x = element_blank(),
        plot.title = element_text(size = 12))
ggI.III <- ggplot(pca.m, aes(x = PC1, y = PC3, color = condition)) +
  geom_point(size = 2)+
  geom_text(aes(label = sample), size = 2, color = "black")+
  labs(title = "PC1 x PC3",
       x = pcI,
       y = pcIII) +
  guides(color = "none")+
  scale_color_manual(values = c("brown2", "darkslategray3"))+
  theme(axis.title.x = element_blank(),
        plot.title = element_text(size = 12))
ggI.IV <- ggplot(pca.m, aes(x = PC1, y = PC4, color = condition)) +
  geom_point(size = 2)+
  geom_text(aes(label = sample), size = 2, color = "black")+
  labs(title = "PC1 x PC4",
       x = pcI,
       y = pcIV) +
  guides(color = "none")+
  scale_color_manual(values = c("brown2", "darkslategray3"))+
  theme(plot.title = element_text(size = 12))
ggI.V <- ggplot(pca.m, aes(x = PC1, y = PC5, color = condition)) +
  geom_point(size = 2)+
  geom_text(aes(label = sample), size = 2, color = "black")+
  labs(title = "PC1 x PC5",
       x = pcI,
       y = pcV) +
  guides(color = "none")+
  scale_color_manual(values = c("brown2", "darkslategray3"))+
  theme(plot.title = element_text(size = 12))

(ggI.II + ggI.III + ggI.IV + ggI.V) +
  plot_annotation(title = "PCA for the 500 most variable miRNAs")

ggsave("04_pca_panel_500_mvt.png",
       path = out, width = 7, height = 7)
dev.off()
