# =========================================================================== #
#### ===================== TARGET RNASEQ SNV ANALYSIS ==================== ####
# =========================================================================== #
# Date: 08.set.2026
### Agilent target RNA-seq analysis identified SNV in our PDX samples. 
## This script filters .tsv file generated by DRAGEN processing and Pulga's 
## pipeline to identify variants. For visualization of results,
## oncoplot is used. 
# <-- INPUT:
## + all snv variants file
## + a file with the genes present in rna enrichment probe panel
# --> OUTPUT:
## + filtered snv variants with desired vaf (.csv)
## + oncoplot (.png)
# =========================================================================== #
#### 0. Libraries -------------------------------------------------------- ####
# =========================================================================== #
library(readr)
library(ComplexHeatmap)
library(tidyverse)
# =========================================================================== #
#### 1. Inputs ----------------------------------------------------------- ####
# =========================================================================== #
## 1.1. All variants file -------------------------------------------------- ##
snv <- readr::read_tsv("D:/rna_panel/all-variants-2026-08-27-revel-go-intervar.tsv")
snv <- as.data.frame(snv)
## 1.2. List of genes present in rna panel --------------------------------- ##
gn.panel <- read.csv("../msc_work/agilent_rnaseq/AllPDX_RNAPanelGeneExpression_310826.csv", sep = ";")
gn.panel <- gn.panel$gene_symbol
gn.panel <- gn.panel[3:605]
## 1.3. Output path -------------------------------------------------------- ##
out <- "../msc_work/agilent_rnaseq/"
# =========================================================================== #
#### 2. Filters ---------------------------------------------------------- ####
# =========================================================================== #
## 2.1. Filter only the genes present in the panel ------------------------- ##
snvf <- snv[snv$SYMBOL %in% gn.panel,] 
## 2.2. Remove variants with low sequencing deth --------------------------- ##
snvf$DP <- as.numeric(snvf$DP)
snvf <- snvf[snvf$DP >= 10,] 
## 2.3. Remove variants that not PASS quality checks ----------------------- ##
snvf <- snvf[snvf$FILTER == "PASS",] #3
## 2.4. Remove SNV with high frequency in the population (gE≤0.01 and “.”) - ##
snv$gnomADe_AF <- as.numeric(snv$gnomADe_AF)
snvf <- snvf[snvf$gnomADe_AF <= 0.01| is.na(snvf$gnomADe_AF),] #4
## 2.5. Keep exonic variants only ------------------------------------------ ##
snvf <- snvf[snvf$EXON != ".",] #5
snvf <- snvf[snvf$INTRON == ".",]
## 2.6. Remove variants with "UTR" and "synonymous" in Consequence --------- ##
snvf <- snvf[!grepl("UTR", snvf$Consequence), ] #6
snvf <- snvf[!grepl("synonymous", snvf$Consequence), ]
## 2.7. Keep pathogenic and VUS variants (according to CLINSIG) ------------ ##
snvf <- snvf[grepl("pathogenic|likely_pathogenic|uncertain_significance|\\.",
                   snvf$CLIN_SIG),] #7
## 2.8. Only for VUS and “.” in CLINSIG, exclude when both SIFT and Polyphen ##
# are tolerated and (benign or unknown) respectively ----------------------- ##
## 2.8.1. Grep for each condition ------------------------------------------ ##
is.vus          <- grepl("uncertain_significance|\\.", snvf$CLIN_SIG) #8
sift.tolerated  <- grepl("tolerated", snvf$SIFT, ignore.case = TRUE)
polyphen.benign <- grepl("benign|unknown", snvf$PolyPhen, ignore.case = TRUE)
## 2.8.2. Get variants that obey all conditions (AND) and remove them ------ ##
rmove <- is.vus & sift.tolerated & polyphen.benign
snvf <- snvf[!rmove, ]
## 2.9. Remove Existing Variance with "rs" that is CLIN_SIG = “.” and        ##
# without Existing Variance with "cos" ------------------------------------- ##
## 2.9.1. Grep for each Existing Variance condition ------------------------ ##
hv.cos <- snvf[grepl("cos", snvf$Existing_variation, ignore.case = TRUE),]
hv.rs  <- snvf[grepl("rs", snvf$Existing_variation, ignore.case = TRUE),]
## 2.9.2. Get the intersection between to two conditions ------------------- ##
intsct <- hv.rs[intersect(rownames(hv.rs),rownames(hv.cos)),]
## 2.9.3. Remove the disjoint from 'rs' and 'cos', with '.' in CLIN_SIG ---- ##
rm.rs <- hv.rs[!rownames(hv.rs) %in% rownames(intsct),] # 9
rm.rs <- rm.rs[grepl("\\.",rm.rs$CLIN_SIG),]
snvf <- snvf[!rownames(snvf) %in% rownames(rm.rs),]

snvf2 <- snvf[!grepl("\\.", snvf$CLIN_SIG),]
snvf3 <- snvf[!grepl("\\.|uncertain|conflicting", snvf$CLIN_SIG),]

## 2.10. Filter the desired vaf -------------------------------------------- ##
snvf3$AF...54 <- as.numeric(snvf3$AF...54)
snvf5 <- snvf3[snvf3$AF...54 >= 0.05,]
snvf30 <- snvf3[snvf3$AF...54 >= 0.3,]
## 2.11. Write .csv files ------------------------------------------------- ##
write.csv(snvf5, file.path(out, "20260910_SNV_vaf5.csv"),
          row.names = F)
write.csv(snvf30, file.path(out, "20260910_SNV_vaf30.csv"),
          row.names = F)
# =========================================================================== #
#### 3. Prepare data for oncoplot ---------------------------------------- ####
# =========================================================================== #
## 3.1. Create data frame with only necessary columns ---------------------- ##
data <- data.frame(Sample = snvf30$SAMPLE,
                   Gene = snvf30$SYMBOL,
                   Variant = snvf30$Consequence)
## 3.2. Separate variants present on the same gene ------------------------- ##
data <- data %>%
  separate_rows(Variant, sep = "&") 
data <- data %>%
  group_by(Sample, Gene) %>%
  summarise(Variant = paste(unique(Variant), collapse = ";"),
            .groups = "drop")
## 3.3. Remove empty row --------------------------------------------------- ##
data <- data[!apply(data == "", 1, all),] 
## 3.4. Transform data to matrix format ------------------------------------ ##
mtx <- pivot_wider(data, names_from = Sample, values_from = Variant,
                   values_fill = "",
                   values_fn = ~ paste(.x, collapse = ";"))
mtx <- column_to_rownames(mtx, var = "Gene")
# =========================================================================== #
#### 4. Oncoplot --------------------------------------------------------- ####
# =========================================================================== #
## 4.1. Create function to separate variation types ------------------------ ##
get_type_fun <- function(x) strsplit(x, ";")[[1]]
## 4.2. Create variation annotation ---------------------------------------- ##
## 4.2.1. Color ------------------------------------------------------------ ##
col <- c("splice_donor_variant" = "#008000",
         "splice_donor_5th_base_variant" = "red",
         "coding_sequence_variant" = "yellow",
         "intron_variant" = "blue",
         "missense_variant" = "darkolivegreen",
         "frameshift_variant" = "black",
         "inframe_insertion" = "orange",
         "inframe_deletion" = "purple",
         "splice_region_variant" = "cyan3",
         "splice_donor_region_variant" = "pink",
         "splice_acceptor_variant" = "magenta",
         "protein_altering_variant" = "orangered",
         "stop_gained" = "steelblue",
         "non_coding_transcript_exon_variant" = "brown")
## 4.2.2. And form --------------------------------------------------------- ##
alter.fun = list(background = alter_graphic("rect", fill = "#CCCCCC"),  
                 splice_donor_variant = alter_graphic("rect",
                                                      fill = col["splice_donor_variant"]),
                 splice_donor_5th_base_variant = alter_graphic("rect",
                                                               fill = col["splice_donor_5th_base_variant"]),
                 coding_sequence_variant = alter_graphic("rect",
                                                         fill = col["coding_sequence_variant"]),
                 intron_variant = alter_graphic("rect", 
                                                fill = col["intron_variant"],
                                                height = 0.7),
                 missense_variant = alter_graphic("rect", 
                                                  fill = col["missense_variant"],
                                                  height = 0.5),
                 frameshift_variant = alter_graphic("rect",
                                                    fill = col["frameshift_variant"],
                                                    height = 0.3),
                 inframe_insertion = alter_graphic("rect",
                                                   fill = col["inframe_insertion"]),
                 inframe_deletion = alter_graphic("rect", 
                                                  fill = col["inframe_deletion"]),
                 splice_region_variant = alter_graphic("rect", 
                                                       fill = col["splice_region_variant"]),
                 splice_donor_region_variant = alter_graphic("rect", 
                                                             fill = col["splice_donor_region_variant"]),
                 splice_acceptor_variant = alter_graphic("rect",
                                                         fill = col["splice_acceptor_variant"]),
                 protein_altering_variant = alter_graphic("rect", 
                                                          fill = col["protein_altering_variant"]),
                 stop_gained = alter_graphic("rect",
                                             fill = col["stop_gained"]),
                 non_coding_transcript_exon_variant = alter_graphic("rect",
                                                                    fill = col["non_coding_transcript_exon_variant"]))
## 4.3. Define legend parameters ------------------------------------------- ##
htmp.leg = list(title = "Consequence",
                at = c("splice_donor_variant",
                       "splice_donor_5th_base_variant",
                       "coding_sequence_variant",
                       "intron_variant",
                       "missense_variant",
                       "frameshift_variant",
                       "inframe_insertion",
                       "inframe_deletion",
                       "splice_region_variant",
                       "splice_donor_region_variant",
                       "splice_acceptor_variant",
                       "protein_altering_variant",
                       "stop_gained",
                       "non_coding_transcript_exon_variant"), 
                labels = c("splice_donor_variant",
                           "splice_donor_5th_base_variant",
                           "coding_sequence_variant",
                           "intron_variant",
                           "missense_variant",
                           "frameshift_variant",
                           "inframe_insertion",
                           "inframe_deletion",
                           "splice_region_variant",
                           "splice_donor_region_variant",
                           "splice_acceptor_variant",
                           "protein_altering_variant",
                           "stop_gained",
                           "non_coding_transcript_exon_variant"))
## 4.4. Get frequencies to define most altered genes ----------------------- ##
gn.freq <- rowSums(mtx != "")
top.gn <- names(sort(gn.freq, decreasing = TRUE)[1:30])
mtxf <- mtx[top.gn, ]
## 4.5. Print oncoplot and save image -------------------------------------- ##
png(file.path(out, "20260910_oncoplot_vaf30_v3.png"),
    width = 10, height = 7, units = "in", res = 300)
oncoPrint(mtxf,
          alter_fun = alter.fun, col = col, 
          remove_empty_columns = TRUE, remove_empty_rows = TRUE,
          heatmap_legend_param = htmp.leg,
          alter_fun_is_vectorized = FALSE, 
          column_title = "Oncoprint for vaf 30%")
dev.off()
